server:
  port: 8088

spring:
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/payments/**
              filters:
                - RewritePath=/payments/?(?<remaining>.*), /${remaining}

            - id: notification-service
              uri: lb://NOTIFICATION-SERVICE
              predicates:
                - Path=/notifications/**
              filters:
                - RewritePath=/notifications/?(?<remaining>.*), /${remaining}

            - id: wallet-service
              uri: lb://WALLET-SERVICE
              predicates:
                - Path=/wallets/**
              filters:
                - RewritePath=/wallets/?(?<remaining>.*), /${remaining}

            - id: transaction-service
              uri: lb://TRANSACTION-SERVICE
              predicates:
                - Path=/transactions/**
              filters:
                - RewritePath=/transactions/?(?<remaining>.*), /${remaining}

            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**
              filters:
                - RewritePath=/users/?(?<remaining>.*), /${remaining}

            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**
              filters:
                - RewritePath=/auth/?(?<remaining>.*), /${remaining}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
