spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: localhost
      port: 6379  
jwt:
  access:
    expiration: 900000

  refresh:
    expiration: 604800000

  secret: ${JWT_SECRET}

server:
  port: 8082

management:
  tracing:
    sampling:
      probability: 1.0

  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces  

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
