spring:
  datasource:
    url: jdbc:postgresql://notification-db-prod:5432/notification_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

server:
  port: 9097

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka