spring:
  application:
    name: transaction-service

management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: "Transaction Service"
    description: "Transaction Management Service"
    version: "1.0"

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost