spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payflow_user_test
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 7083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka