spring:
  application:
    name: user-service
  
management:
  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: "User Service"
    description: "User Management Service"
    version: "1.0"

eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
