spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/wallet_test_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop

server:
  port: 7084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka